#!/usr/bin/env bash
#
# Stage 6: Output Generation
#
# Transforms the synthesized timeline.json into multiple output formats:
#   - Markdown timeline pack (primary deliverable)
#   - JSON export (system integration)
#   - CSV export (spreadsheet analysis)
#   - HTML interactive timeline (visual review)
#
# No API calls. All transformations are local Python.

run_stage_6_output() {
  stage "6" "Output Generation"

  local output_dir="${TIMELINE_DIR}/output"
  local log_file="${TIMELINE_DIR}/logs/stage-6.log"
  ensure_dir "$output_dir"

  if [[ ! -f "${output_dir}/timeline.json" ]]; then
    fail "No synthesized timeline found. Did Stage 5 complete?"
    return 1
  fi

  # Determine requested formats
  local formats
  formats="$(config_get output_formats 'markdown json')"
  log "Output formats: $formats"

  # Load matter context
  local case_name
  case_name="$(config_get case_name '(not set)')"
  local case_number
  case_number="$(config_get case_number '')"

  # Always generate markdown (primary format)
  generate_markdown_pack "$output_dir" "$case_name" "$case_number"

  # Conditional formats
  if [[ "$formats" == *"json"* ]]; then
    # JSON is already generated by Stage 5 as timeline.json
    ok "JSON output: ${output_dir}/timeline.json"
  fi

  if [[ "$formats" == *"csv"* ]]; then
    generate_csv_export "$output_dir"
  fi

  if [[ "$formats" == *"html"* ]]; then
    generate_html_timeline "$output_dir" "$case_name"
  fi

  # Generate glass box audit trail
  generate_audit_trail "$output_dir"

  divider
  ok "Stage 6 complete. Outputs in ${output_dir}/"
  log "Files generated:"
  ls -la "$output_dir"/ 2>/dev/null | tail -n +2
  return 0
}

# ─── Markdown Timeline Pack ───────────────────────────────────────────────

generate_markdown_pack() {
  local output_dir="$1"
  local case_name="$2"
  local case_number="$3"
  local md_file="${output_dir}/timeline-pack.md"

  log "Generating markdown timeline pack..."

  python3 - "${output_dir}/timeline.json" "$md_file" "$case_name" "$case_number" \
    "$(config_get objective 'case strategy')" \
    "$(config_get side 'plaintiff')" \
    "$(config_get governing_law '')" \
    "$(config_get forum '')" \
    <<'PYEOF'
import json, sys
from datetime import datetime

timeline_file = sys.argv[1]
md_file = sys.argv[2]
case_name = sys.argv[3]
case_number = sys.argv[4]
objective = sys.argv[5]
side = sys.argv[6]
governing_law = sys.argv[7]
forum = sys.argv[8]

with open(timeline_file) as f:
    data = json.load(f)

meta = data.get('metadata', {})
mc = data.get('master_chronology', [])
it = data.get('issue_timelines', {})
et = data.get('entity_timelines', {})
cr = data.get('contradiction_resolutions', [])
gr = data.get('gap_register', [])
dc = data.get('deadline_calendar', [])
sa = data.get('strategic_assessment', {})

lines = []
w = lines.append

w(f'# Case Timeline Pack -- {case_name or meta.get("case_name", "(Matter)")}\n')

# Executive snapshot
w('## 1. Executive Snapshot\n')
w(f'- **Matter**: {case_name} {case_number}')
w(f'- **Objective**: {objective}')
w(f'- **Side represented**: {side}')
w(f'- **Governing forum/law**: {forum} / {governing_law}')
w(f'- **Chronology confidence**: {meta.get("confidence_overall", "MEDIUM")}')
w(f'- **Generated**: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}')
w(f'- **Timeline events**: {len(mc)}')
w(f'- **Contradictions found**: {len(cr)}')
w(f'- **Gaps identified**: {len(gr)}')
w('')

# Strategic risks
if sa:
    w('### Top Timeline Risks')
    for i, vuln in enumerate(sa.get('vulnerabilities', [])[:5], 1):
        if isinstance(vuln, dict):
            w(f'{i}. {vuln.get("description", str(vuln))}')
        else:
            w(f'{i}. {vuln}')
    w('')

# Master chronology
w('## 2. Master Chronology\n')
w('| # | Date | Precision | Event | Actors | Sources | Confidence |')
w('|---|------|-----------|-------|--------|---------|------------|')
for i, evt in enumerate(mc, 1):
    date = evt.get('normalized_date', evt.get('date', ''))
    prec = evt.get('precision', '')
    desc = evt.get('event_description', evt.get('description', evt.get('event', '')))
    actors = ', '.join(evt.get('actors', []))
    sources = ', '.join(evt.get('source_references', [evt.get('source_id', '')]))
    conf = evt.get('confidence', '')
    if isinstance(conf, float):
        conf = f'{conf:.2f}'
    w(f'| {i} | {date} | {prec} | {desc} | {actors} | {sources} | {conf} |')
w('')

# Issue timelines
if it:
    w('## 3. Issue Timelines\n')
    for issue_name, events in it.items():
        w(f'### {issue_name}\n')
        w('| Date | Event | Sources | Confidence |')
        w('|------|-------|---------|------------|')
        for evt in events:
            date = evt.get('normalized_date', evt.get('date', ''))
            desc = evt.get('event_description', evt.get('description', evt.get('event', '')))
            sources = ', '.join(evt.get('source_references', []))
            conf = evt.get('confidence', '')
            if isinstance(conf, float):
                conf = f'{conf:.2f}'
            w(f'| {date} | {desc} | {sources} | {conf} |')
        w('')

# Entity timelines
if et:
    w('## 4. Entity Timelines\n')
    for entity_name, events in et.items():
        w(f'### {entity_name}\n')
        w('| Date | Event | Document Basis |')
        w('|------|-------|----------------|')
        for evt in events:
            date = evt.get('normalized_date', evt.get('date', ''))
            desc = evt.get('event_description', evt.get('description', evt.get('event', '')))
            sources = ', '.join(evt.get('source_references', []))
            w(f'| {date} | {desc} | {sources} |')
        w('')

# Contradiction register
if cr:
    w('## 5. Contradiction Register\n')
    w('| # | Type | Events | Severity | Resolution |')
    w('|---|------|--------|----------|------------|')
    for i, c in enumerate(cr, 1):
        ctype = c.get('type', '')
        events_str = ', '.join(c.get('event_ids', []))
        sev = c.get('severity', '')
        res = c.get('resolution', c.get('recommended_resolution', ''))
        w(f'| {i} | {ctype} | {events_str} | {sev} | {res} |')
    w('')

# Gap register
if gr:
    w('## 6. Gap Register\n')
    w('| # | Period | Missing Information | Impact | Recommended Action |')
    w('|---|--------|---------------------|--------|-------------------|')
    for i, g in enumerate(gr, 1):
        period = f'{g.get("period_start", "")} to {g.get("period_end", "")}'
        desc = g.get('description', '')
        impact = g.get('impact', '')
        action = g.get('recommended_action', '')
        w(f'| {i} | {period} | {desc} | {impact} | {action} |')
    w('')

# Deadline calendar
if dc:
    w('## 7. Deadline Risk Calendar\n')
    w('| Trigger Event | Rule/Order | Deadline | Status | Risk Level |')
    w('|---------------|------------|----------|--------|------------|')
    for d in dc:
        trigger = d.get('trigger_event', '')
        rule = d.get('rule_or_order', d.get('rule', ''))
        deadline = d.get('deadline', '')
        status = d.get('status', '')
        risk = d.get('risk_level', d.get('risk', ''))
        w(f'| {trigger} | {rule} | {deadline} | {status} | {risk} |')
    w('')

# Strategic assessment
if sa:
    w('## 8. Strategic Assessment\n')
    if sa.get('strengths'):
        w('### Strengths')
        for s in sa['strengths']:
            if isinstance(s, dict):
                w(f'- {s.get("description", str(s))}')
            else:
                w(f'- {s}')
        w('')
    if sa.get('vulnerabilities'):
        w('### Vulnerabilities')
        for v in sa['vulnerabilities']:
            if isinstance(v, dict):
                w(f'- {v.get("description", str(v))}')
            else:
                w(f'- {v}')
        w('')
    if sa.get('recommended_actions'):
        w('### Recommended Actions')
        for a in sa['recommended_actions']:
            if isinstance(a, dict):
                w(f'- {a.get("description", str(a))}')
            else:
                w(f'- {a}')
        w('')

# Footer
w('---\n')
w(f'*Generated by legalcode-case-timeline-builder on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}*')
w('')
w('> **Disclaimer**: This timeline was constructed with AI assistance and must be reviewed')
w('> by qualified legal counsel before use. All events should be verified against original')
w('> source documents. AI-extracted dates and events may contain errors.')

with open(md_file, 'w') as f:
    f.write('\n'.join(lines))

print(f'Markdown timeline pack written: {md_file}')
PYEOF

  ok "Markdown: ${md_file}"
}

# ─── CSV Export ────────────────────────────────────────────────────────────

generate_csv_export() {
  local output_dir="$1"
  local csv_file="${output_dir}/timeline-events.csv"

  log "Generating CSV export..."

  python3 - "${output_dir}/timeline.json" "$csv_file" <<'PYEOF'
import json, csv, sys

with open(sys.argv[1]) as f:
    data = json.load(f)

events = data.get('master_chronology', [])
fieldnames = [
    'event_id', 'date', 'precision', 'event_type', 'description',
    'actors', 'sources', 'confidence', 'status'
]

with open(sys.argv[2], 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for evt in events:
        writer.writerow({
            'event_id': evt.get('event_id', ''),
            'date': evt.get('normalized_date', evt.get('date', '')),
            'precision': evt.get('precision', ''),
            'event_type': evt.get('event_type', ''),
            'description': evt.get('event_description', evt.get('description', evt.get('event', ''))),
            'actors': '; '.join(evt.get('actors', [])),
            'sources': '; '.join(evt.get('source_references', [])),
            'confidence': evt.get('confidence', ''),
            'status': evt.get('status', ''),
        })

print(f'CSV export: {len(events)} events written to {sys.argv[2]}')
PYEOF

  ok "CSV: ${csv_file}"
}

# ─── HTML Timeline ─────────────────────────────────────────────────────────

generate_html_timeline() {
  local output_dir="$1"
  local case_name="$2"
  local html_file="${output_dir}/timeline.html"

  log "Generating HTML timeline..."

  python3 - "${output_dir}/timeline.json" "$html_file" "$case_name" <<'PYEOF'
import json, sys, html

with open(sys.argv[1]) as f:
    data = json.load(f)

html_file = sys.argv[2]
case_name = html.escape(sys.argv[3])
events = data.get('master_chronology', [])

rows = []
for evt in events:
    date = html.escape(str(evt.get('normalized_date', evt.get('date', ''))))
    desc = html.escape(str(evt.get('event_description', evt.get('description', evt.get('event', '')))))
    actors = html.escape(', '.join(evt.get('actors', [])))
    sources = html.escape(', '.join(evt.get('source_references', [])))
    conf = evt.get('confidence', 0)
    conf_class = 'high' if conf >= 0.8 else ('medium' if conf >= 0.6 else 'low')
    rows.append(f'''
    <tr class="conf-{conf_class}">
      <td class="date">{date}</td>
      <td>{desc}</td>
      <td>{actors}</td>
      <td class="sources">{sources}</td>
      <td class="confidence">{conf:.2f if isinstance(conf, float) else conf}</td>
    </tr>''')

html_content = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Timeline -- {case_name}</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; margin: 2rem; color: #1a1a1a; }}
  h1 {{ border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
  th {{ background: #1e293b; color: white; padding: 0.75rem; text-align: left; position: sticky; top: 0; }}
  td {{ padding: 0.5rem 0.75rem; border-bottom: 1px solid #e2e8f0; vertical-align: top; }}
  tr:hover {{ background: #f1f5f9; }}
  .date {{ white-space: nowrap; font-family: monospace; }}
  .sources {{ font-size: 0.85em; color: #64748b; }}
  .confidence {{ text-align: center; font-family: monospace; }}
  .conf-high td {{ border-left: 3px solid #22c55e; }}
  .conf-medium td {{ border-left: 3px solid #eab308; }}
  .conf-low td {{ border-left: 3px solid #ef4444; }}
  .legend {{ display: flex; gap: 1.5rem; margin: 1rem 0; font-size: 0.9em; }}
  .legend span {{ display: inline-flex; align-items: center; gap: 0.3rem; }}
  .dot {{ width: 12px; height: 12px; border-radius: 50%; display: inline-block; }}
  .dot-high {{ background: #22c55e; }}
  .dot-medium {{ background: #eab308; }}
  .dot-low {{ background: #ef4444; }}
  .disclaimer {{ background: #fef3c7; border: 1px solid #f59e0b; padding: 1rem; border-radius: 0.5rem; margin-top: 2rem; font-size: 0.9em; }}
  .stats {{ color: #64748b; margin-bottom: 1rem; }}
</style>
</head>
<body>
<h1>Case Timeline -- {case_name}</h1>
<p class="stats">{len(events)} events | Generated {__import__("datetime").datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}</p>
<div class="legend">
  <span><span class="dot dot-high"></span> High confidence (0.80+)</span>
  <span><span class="dot dot-medium"></span> Medium confidence (0.60-0.79)</span>
  <span><span class="dot dot-low"></span> Low confidence (&lt;0.60)</span>
</div>
<table>
<thead>
<tr><th>Date</th><th>Event</th><th>Actors</th><th>Sources</th><th>Confidence</th></tr>
</thead>
<tbody>
{"".join(rows)}
</tbody>
</table>
<div class="disclaimer">
<strong>Disclaimer:</strong> This timeline was constructed with AI assistance.
All events must be verified against original source documents by qualified legal counsel
before use in any legal proceeding.
</div>
</body>
</html>'''

with open(html_file, 'w') as f:
    f.write(html_content)

print(f'HTML timeline: {len(events)} events written to {html_file}')
PYEOF

  ok "HTML: ${html_file}"
}

# ─── Glass Box Audit Trail ────────────────────────────────────────────────

generate_audit_trail() {
  local output_dir="$1"
  local audit_file="${output_dir}/audit-trail.yaml"

  log "Generating audit trail..."

  python3 - \
    "${TIMELINE_DIR}/consolidated/summary.json" \
    "${TIMELINE_DIR}/validated/validation.json" \
    "${output_dir}/timeline.json" \
    "$audit_file" \
    "$(config_get case_name '')" \
    "$(config_get governing_law '')" \
    "$OPUS_MODEL" "$SONNET_MODEL" "$HAIKU_MODEL" \
    <<'PYEOF'
import json, sys, os
from datetime import datetime

summary_file = sys.argv[1]
validation_file = sys.argv[2]
timeline_file = sys.argv[3]
audit_file = sys.argv[4]
case_name = sys.argv[5]
governing_law = sys.argv[6]
opus = sys.argv[7]
sonnet = sys.argv[8]
haiku = sys.argv[9]

summary = {}
if os.path.exists(summary_file):
    with open(summary_file) as f:
        summary = json.load(f)

validation = {}
if os.path.exists(validation_file):
    with open(validation_file) as f:
        validation = json.load(f)

timeline = {}
if os.path.exists(timeline_file):
    with open(timeline_file) as f:
        timeline = json.load(f)

qs = validation.get('quality_summary', {})
mc = timeline.get('master_chronology', [])
cr = timeline.get('contradiction_resolutions', [])
gr = timeline.get('gap_register', [])

yaml_lines = [
    'glass_box:',
    '  skill_name: "legalcode-case-timeline-builder"',
    '  skill_version: "1.0"',
    '  topic: "litigation chronology construction"',
    f'  jurisdiction: "{governing_law}"',
    f'  case_name: "{case_name}"',
    '',
    '  # Processing metadata',
    f'  processing_completed: "{datetime.utcnow().isoformat()}Z"',
    '',
    '  # Document corpus',
    '  corpus_summary:',
    f'    date_files_processed: {summary.get("date_files_processed", 0)}',
    f'    entity_files_processed: {summary.get("entity_files_processed", 0)}',
    '',
    '  # Extraction metrics',
    '  extraction_summary:',
    f'    events_raw: {summary.get("events", {}).get("raw", 0)}',
    f'    events_deduplicated: {summary.get("events", {}).get("deduplicated", 0)}',
    f'    entities_raw: {summary.get("entities", {}).get("raw", 0)}',
    f'    entities_deduplicated: {summary.get("entities", {}).get("deduplicated", 0)}',
    f'    relationships: {summary.get("relationships", 0)}',
    '',
    '  # Model usage',
    '  models_used:',
    f'    orchestrator: "{opus}"',
    f'    extraction: "{haiku}"',
    f'    validation: "{sonnet}"',
    '',
    '  # Quality metrics',
    f'  master_chronology_events: {len(mc)}',
    f'  contradictions_found: {len(cr)}',
    f'  gaps_identified: {len(gr)}',
    f'  overall_quality: "{qs.get("overall_quality", "UNKNOWN")}"',
    '',
    '  # Limitations',
    '  limitations:',
    '    - "AI extraction may miss implicit or contextual dates"',
    '    - "OCR quality affects accuracy for scanned documents"',
    '    - "Jurisdiction-specific procedural rules require counsel validation"',
    '    - "Cross-document entity resolution is probabilistic"',
    '    - "Approximate dates may be incorrectly normalized"',
    '',
    '  # Review status',
    '  reviewer: "AI-assisted; human legal review required"',
    '  review_status: "PENDING"',
]

with open(audit_file, 'w') as f:
    f.write('\n'.join(yaml_lines) + '\n')

print(f'Audit trail written to {audit_file}')
PYEOF

  ok "Audit trail: ${audit_file}"
}
